SELECT *
FROM VEM_SER.PAIS
ORDER BY ID_PAIS  DESC;

SELECT LOGRADOURO, CEP
FROM VEM_SER.ENDERECO
WHERE UPPER(LOGRADOURO) LIKE '%A%';

SELECT *
FROM VEM_SER.ENDERECO
WHERE SUBSTR(CEP, -1) = '0';

SELECT *
FROM VEM_SER.ENDERECO
WHERE UPPER(LOGRADOURO) LIKE 'RUA%'
ORDER BY CEP DESC;

SELECT COUNT(*) AS QUANTIDADE_DE_ENDERECOS
FROM VEM_SER.ENDERECO;

SELECT ID_CIDADE, COUNT(*) AS QUANTIDADE_DE_ENDERECOS
FROM VEM_SER.ENDERECO
GROUP BY ID_CIDADE;